const OfferData = [
  {
    id: `apartment-1`,
    price: 120,
    stars: 4,
    title: `Beautiful & luxurious apartment at great location`,
    type: `Apartment`,
    img: `apartment-01.jpg`,
    isFavorite: false,
    isPremium: true,
  },
  {
    id: `private-1`,
    price: 80,
    stars: 4,
    title: `Wood and stone place`,
    type: `Private room`,
    img: `room.jpg`,
    isFavorite: true,
    isPremium: false,
  },
  {
    id: `apartment-2`,
    price: 132,
    stars: 4,
    title: `Canal View Prinsengratch`,
    type: `Apartment`,
    img: `apartment-02.jpg`,
    isFavorite: false,
    isPremium: false,
  },
  {
    id: `apartment-3`,
    price: 180,
    stars: 5,
    title: `Nice, cozy, warm big bed apartment`,
    type: `Apartment`,
    img: `apartment-03.jpg`,
    isFavorite: false,
    isPremium: true,
  },
  {
    id: `private-2`,
    price: 80,
    stars: 4,
    title: `Wood and stone place`,
    type: `Private room`,
    img: `room.jpg`,
    isFavorite: true,
    isPremium: false,
  },
];

export {OfferData};
